version: '3.3'
services:
  fastapi-app:
    container_name: celery_test_fastapi_app
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    ports:
      - 8022:8000
    depends_on:
    - rabbitmq
    - redis


  rabbitmq:
    container_name: celery_test_rabbitmq
    image: rabbitmq:3.11.2-management-alpine
    restart: always
    ports:
      - 15677:15672

  redis:
    container_name: celery_test_redis
    image: redis:alpine
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: celery_worker.dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - redis
    deploy:
      replicas: 1

  flower:
    container_name: celery_test_flower
    image: mher/flower:1.2
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - FLOWER_URL=http://celery_worker:5555
    restart: always
    ports:
      - 5558:5555
    depends_on:
      - celery_worker
      - rabbitmq